name: Alpine Linux Packages

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master
    - release/*
  pull_request:
    branches:
    - main
    - master
    - release/*

concurrency:
  # Cancel any workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: package-linux-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-alpine-packages:
    name: Generate Alpine Packages
    needs: []
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { friendlyName: "Alpine 3.20 x64", config: "Release", os: "alpine-3.20", arch: "x64", tls: "openssl3", image: "mcr.microsoft.com/dotnet/sdk:8.0-alpine3.20-amd64" },
          # { friendlyName: "Alpine 3.20 ARM64", config: "Release", os: "alpine-3.20", arch: "arm64", tls: "openssl3", image: "mcr.microsoft.com/dotnet/sdk:8.0-alpine3.20-arm64v8" },
          # { friendlyName: "Alpine 3.20 ARM32", config: "Release", os: "alpine-3.20", arch: "arm", tls: "openssl3", image: "mcr.microsoft.com/dotnet/sdk:8.0-alpine3.20-arm32v7" },
        ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.vec.image }}
      env:
        REPO_TAR_URL: ${{ github.api_url }}/repos/${{ github.repository }}/tarball/${{ github.sha }}
        REPO: https://github.com/${{ github.repository }}
        SHA: ${{ github.sha }}
        TARGETARCH: ${{ matrix.vec.arch }}
    steps:
    - name: Get Files
      run: |
        wget $REPO_URL/packaging/github-actions/APKBUILD
        wget $REPO_URL/scripts/alpine-configure-packaging-key.sh
        wget $REPO_URL/scripts/alpine-packaging-prepare-script.sh
      env:
        REPO_URL: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}

    - name: Prepare Image for Packaging # This step is needed only for testing the package.
      run: |
        ./alpine-packaging-prepare-script.sh
        mkdir -p /home/packaging/tools
        cp APKBUILD /home/packaging/tools
        chown -R packaging:abuild /home/packaging/tools
    
    - name: Generate Keys for Test Packaging
      run: |
        su packaging -c "abuild-keygen -n"
        find /home/packaging/.abuild -name '*.rsa' -exec ./alpine-configure-packaging-key.sh {} \;

    - name: Build Package
      run: |
        # msquic is using submodules and we need to get them inside
        su packaging -c "abuild snapshot"
        su packaging -c "abuild checksum"
        su packaging -c "abuild -r"

    - name: Upload Package
      uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a
      with:
        name: ${{ matrix.vec.friendlyName }}-package
        path: /home/packaging/packages/packaging/**/*.apk

  